# Generated by Django 3.2 on 2021-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=1, max_length=150, verbose_name='Контактный телефон'),
            preserve_default=False,
        ),
    ]
