# Generated by Django 3.2 on 2021-10-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Фото техники')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Стоимость услуги')),
                ('price_description', models.CharField(choices=[('hour', 'час'), ('flight', 'рейс'), ('km', 'км'), ('cub.m.', 'куб.м.'), ('kg', 'кг')], default='hour', max_length=50, verbose_name='Описание стоимости')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Контактный телефон')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Время начало')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Время конца')),
                ('status', models.CharField(choices=[('free', 'свободен'), ('busy', 'занят')], default='free', max_length=30, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Стоимость услуги со скидкой')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Техника', to='webapp.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='Комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
