# Generated by Django 3.2 on 2021-10-27 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='advertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Автор объявления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technique',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начало'),
        ),
    ]
