# Generated by Django 3.2 on 2021-10-27 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20211027_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='technique',
            name='advertiser',
            field=models.ManyToManyField(related_name='techniques', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления'),
        ),
    ]
