# Generated by Django 3.2 on 2021-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211027_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=1, max_length=150, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technique',
            name='price_description',
            field=models.CharField(choices=[('hour', 'час'), ('flight', 'рейс'), ('km', 'км'), ('cub.m.', 'куб.м.'), ('kg', 'кг')], default='час', max_length=50, verbose_name='Описание стоимости'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='status',
            field=models.CharField(choices=[('free', 'свободен'), ('busy', 'занят')], default='свободен', max_length=30, verbose_name='Статус'),
        ),
    ]
