# Generated by Django 3.2 on 2021-10-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20211027_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='price_description',
            field=models.CharField(choices=[('час', 'час'), ('рейс', 'рейс'), ('км', 'км'), ('куб.м.', 'куб.м.'), ('кг', 'кг')], default='час', max_length=50, verbose_name='Описание стоимости'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='status',
            field=models.CharField(choices=[('свободен', 'свободен'), ('занят', 'занят')], default='свободен', max_length=30, verbose_name='Статус'),
        ),
    ]
