# Generated by Django 3.2 on 2021-10-30 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_auto_20211030_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='technique',
            name='advertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='auth.user', verbose_name='Автор объявления'),
            preserve_default=False,
        ),
    ]
