# Generated by Django 3.2 on 2021-11-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_order_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='technique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.technique', verbose_name='Комментарий на технику'),
            preserve_default=False,
        ),
    ]
